spring.datasource.url=jdbc:mysql://localhost:3306/budget_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Deepak@12345
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true

server.port=8082

# Google Drive Configuration
# 1. PASTE your Client ID below:
google.drive.client.id=167012020945-o6osmi9kpvda8o0kbnj6ar9o01ch4rdf.apps.googleusercontent.com
# 2. PASTE your Client Secret below:
google.drive.client.secret=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
# 3. PASTE your new Refresh Token below:
google.drive.refresh.token=1//04duT2--YKCf6CgYIARAAGAQSNwF-L9Irp6j0AZy08SEHK8NXAuM0-l-Sd63ADiGiS28ni9TF8fJGFMvoamBqSLwsyRnu5CIivaM

google.drive.folder.id=https://drive.google.com/drive/folders/1QgMbaAqhnocWoSxZIodj2rMdGueLb9fF?usp=drive_link

# 📧 Email Server (SMTP) Configuration
# Required to send physical alert emails to your inbox

spring.mail.host=smtp.gmail.com
spring.mail.port=587
# 1. PASTE your full Gmail address below:
spring.mail.username=nukalasaideepak@gmail.com
# 2. PASTE your 16-character Gmail "App Password" below (NOT your regular password!):
spring.mail.password=mzjs obag ywmc mczg

# Mail SMTP Properties (Don't change these)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
